apiVersion: v1
kind: ResourceQuota
metadata:
  name: bu-a-quota
  namespace: bu-a-workloads
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "20"
    services: "10"
